couple of fixes
lancasterunicompsoc/CompSoc-Website pull request #112
Opened 2024-09-30 15:30 UTC by hugohabicht01

- get rid of bullshit that made the website horrible to interact with
- replace almost all occurences of `role` strings with an 'enum' (due to the recent switch to sqlite)

2024-10-02 09:18 UTC, 456dev requested changes
i might just have a different idea about what is needed, but the ability to link / view 1 "slides" object individually would be useful for linking from the events pages etc.
also remove the bun lockfile for modern yarn

2024-10-04 17:41 UTC, hugohabicht01 commented on bun.lockb
good shout, that file shouldn't have made its way into the commits anyway...

2024-11-11 20:19 UTC, hugohabicht01 commented on prisma/schema.prisma
> +
that gets done by the mimetype field, how we should render it, should mainly depend on the mimetype

2024-11-11 20:19 UTC, hugohabicht01 commented on pages/slides.vue
the links can all be accessed directly

2024-11-11 20:45 UTC, 456dev approved these changes
LGTM

2024-11-11 21:18 UTC, merged